### ISSUE TITLE
I'm getting a UnicodeDecodeError error on startup?

### ISSUE THREAD

**Issue by krathjen** [krathjen/studiolibrary#194]

**Comment by krathjen** [comment]
Email:

> Hello, I followed the instructions step by step and this error keeps showing.

```
# Original exception was:
# Traceback (most recent call last):
#   File "<maya console>", line 2, in <module>
#   File "C:/Users/cesña/Documents/maya/2015-x64/scripts\studiolibrary\__init__.py", line 49, in <module>
#     setup(PACKAGES_PATH)
#   File "C:/Users/cesña/Documents/maya/2015-x64/scripts\studiolibrary\__init__.py", line 45, in setup
#     print 'Adding "{path}" to the sys.path'.format(path=path)
# UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 13: ordinal not in range(128) # ```

**Comment by krathjen** [comment]
This error is because of a non-ASCII character **ñ** in the source path "ces**ñ**a".

At the moment the Studio Library does not support non-ASCII characters in the source path.

Thanks,

Kurt
