### ISSUE TITLE
I'm getting a UnicodeDecodeError error on startup? 

### ISSUE THREAD

**Issue by krathjen** [krathjen/studiolibrary#195]
Email:

> Hello, I followed the instructions step by step and this error keeps showing.

```
# Original exception was:
# Traceback (most recent call last):
#   File "<maya console>", line 2, in <module>
#   File "C:/Users/cesña/Documents/maya/2015-x64/scripts\studiolibrary\__init__.py", line 49, in <module>
#     setup(PACKAGES_PATH)
#   File "C:/Users/cesña/Documents/maya/2015-x64/scripts\studiolibrary\__init__.py", line 45, in setup
#     print 'Adding "{path}" to the sys.path'.format(path=path)
# UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 13: ordinal not in range(128) # ```

**Comment by krathjen** [comment]
This error is because of a non-ASCII character **ñ** in the source path "ces**ñ**a".

At the moment the Studio Library does not support non-ASCII characters in the source path.

Thanks,

Kurt

**Comment by lovelyVOOK** [comment]
Hello! I have the same error, but the path is correct:

import studiolibrary
studiolibrary.main()

Error: UnicodeDecodeError: file D:\Documents\maya\scripts\studiolibrary\src\studiolibrary\utils.py line 907: ascii

**Comment by Salmonart** [comment]
I have a similar error but I have not any non-ascii characters : 

if not os.path.exists(r'D:\Documents\maya\scripts\studiolibrary-2.9.6.b3\src'):
    raise IOError(r'The source path "D:\Documents\maya\scripts\studiolibrary-2.9.6.b3\src" does not exist!')
    
if r'D:\Documents\maya\scripts\studiolibrary-2.9.6.b3\src' not in sys.path:
    sys.path.insert(0, r'D:\Documents\maya\scripts\studiolibrary-2.9.6.b3\src')
    
import studiolibrary
studiolibrary.main()

# Error: UnicodeDecodeError: file D:\Documents\maya\scripts\studiolibrary-2.9.6.b3\src\studiolibrary\utils.py line 574: 'ascii' codec can't decode byte 0xe0 in position 3: ordinal not in range(128) #

**Comment by chilyanin** [comment]
No solutions to fix this ?
