### ISSUE TITLE
Having a folder and item already selected when reopening Studio Library causes object deleted traceback 

### ISSUE THREAD

**Issue by alexwidener** [krathjen/studiolibrary#200]
Maya: 2018.2 
Studio Library: 2.4.0b2
OS: Linux

Steps to reproduce:
1. Select Animation Item in Studio Library.
2. Close Studio Library
3. Reopen Studio Library (verify was still selected)
4. Receive:
```
# Traceback (most recent call last):
#   File "[removed]/latest/studiolibrary/packages/studiolibrarymaya/basepreviewwidget.py", line 209, in resizeEvent
#     self.updateThumbnailSize()
#   File "[removed]/latest/studiolibrary/packages/studiolibrarymaya/basepreviewwidget.py", line 225, in updateThumbnailSize
#     self.ui.thumbnailFrame.setMaximumSize(size)
# RuntimeError: Internal C++ object (PySide2.QtWidgets.QFrame) already deleted.
# Traceback (most recent call last):
#   File "[removed]/latest/studiolibrary/packages/studiolibrarymaya/basepreviewwidget.py", line 209, in resizeEvent
#     self.updateThumbnailSize()
#   File "[removed]/latest/studiolibrary/packages/studiolibrarymaya/basepreviewwidget.py", line 225, in updateThumbnailSize
#     self.ui.thumbnailFrame.setMaximumSize(size)
# RuntimeError: Internal C++ object (PySide2.QtWidgets.QFrame) already deleted.
# Result: <studiolibrarymaya.mayalibrarywidget.MayaLibraryWidget object at 0x7f5e035bffc8> # 
```

Alternative steps to reproduce:
1. Select Animation Item in Studio Library.
2. Close Maya
3. Restart Maya
4. Open Studio Library (verify was still selected)
5. Receive same traceback.

Result:
Traceback

Expected result: 
Item should still be selected, should receive no RuntimeError.

**Comment by krathjen** [comment]
Hey @alexwidener,

Thanks for submitting this issue.

I haven't seen this error message on windows, so I'll try on OSX and Linux soon.

Also, are you reloading any Studio Library modules using the python "reload" command before running the Studio Library?

You could also download and test the following branch to see if it helps.

https://github.com/krathjen/studiolibrary/tree/imp/librarymodel

Let me know how it goes.

Cheers,

Kurt

**Comment by alexwidener** [comment]
No, I'm not using the reload module when this occurs. 

This is starting a fresh scene and _only_ running 

```
import studiolibrary
studiolibrary.main()
```

which is what our users will run. I'll try that branch on Monday whenever I get into work, thanks.
