### ISSUE TITLE
Error: root : No JSON object could be decoded

### ISSUE THREAD

**Issue by mattdiks** [krathjen/studiolibrary#207]
Hey team,

Thanks for the awesome work in creating and supporting studioLibrary. I love it!
Recently something happened and I can't figure it out. I get this error and have to re-path to the root library every time I open Maya.

I have reset prefs and the Maya.env file. I also re-downloaded a fresh set of studioLibrary files.

Thanks for your help!
Matt

import studiolibrary

studiolibrary.main()
# Error: root : No JSON object could be decoded
Traceback (most recent call last):
  File "C:/Users/Joshua/Documents/maya/scripts\studiolibrary\librarywidget.py", line 2028, in readSettings
    data = studiolibrary.readJson(path)
  File "C:/Users/Joshua/Documents/maya/scripts\studiolibrary\cmds.py", line 659, in readJson
    data = json.loads(data)
  File "C:\Program Files\Autodesk\Maya2017\bin\python27.zip\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Autodesk\Maya2017\bin\python27.zip\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Autodesk\Maya2017\bin\python27.zip\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded #

**Comment by krathjen** [comment]
Closing this issue for now.

Please reopen the ticket If your still having issues.

Also, please try the latest version 2.4.0.b60.

Thanks,

Kurt
