### ISSUE TITLE
Exporting "proxy" attributes not working

### ISSUE THREAD

**Issue by mrharris** [krathjen/studiolibrary#220]
When an attribute is driven by a proxy attribute animation fails to export. Only a `pose.json` file is created - no `animation.mb` is created. See attached file to reproduce [proxyAttr_issue.ma.zip](https://github.com/krathjen/studiolibrary/files/2648663/proxyAttr_issue.ma.zip)

The export process also creates additional/undesirable keys on the animCurve (see _after_ pic)
**Before export**
![before_export](https://user-images.githubusercontent.com/1923447/49511225-778d8380-f882-11e8-97c8-58341ff36550.png)

**After export** - notice the 2 additional keys
![after_export](https://user-images.githubusercontent.com/1923447/49511235-7c523780-f882-11e8-8adf-26c997e0dff3.png)

Running the test suite also seem to fail when it gets to the proxy tests, I'm not sure if this is the same issue

```python
import studiolibrary
import mutils.tests
mutils.tests.run()

# Error: mutils.attribute : Cannot GET attribute VALUE for "group|offset|lockedNode|sphere.testProxy"
Traceback (most recent call last):
  File "/home/lharris/dev/studiolibrary/packages/mutils/attribute.py", line 244, in value
    self._value = maya.cmds.getAttr(self.fullname())
ValueError: No object matches name: group|offset|lockedNode|sphere.testProxy # 
# Error: mutils.attribute : Cannot GET attribute TYPE for "group|offset|lockedNode|sphere.testProxy"
Traceback (most recent call last):
  File "/home/lharris/dev/studiolibrary/packages/mutils/attribute.py", line 261, in type
    self._type = maya.cmds.getAttr(self.fullname(), type=True)
ValueError: No object matches name: group|offset|lockedNode|sphere.testProxy # 
# Error: mutils.attribute : Cannot GET attribute TYPE for "group|offset|lockedNode|sphere.testProxy"
Traceback (most recent call last):
  File "/home/lharris/dev/studiolibrary/packages/mutils/attribute.py", line 261, in type
    self._type = maya.cmds.getAttr(self.fullname(), type=True)
ValueError: No object matches name: group|offset|lockedNode|sphere.testProxy # 
```

**Comment by krathjen** [comment]
Hey @mrharris,

Thanks for the information.

I just ran the latest tests (master branch) and they seem to work with Windows 10 and Maya 2019 (Preview Release).

When I get more time, I'll have a look at this in more detail.

Thanks,

Kurt

**Comment by krathjen** [comment]
Hi @mrharris,

Hope you're well.

Just checking to see if this is still an issue for you? 

Thanks,

Kurt

**Comment by artcunha** [comment]
Hi, I'm one of Luke's colleague. Yeah, seems like we're still having the same problems both with the file creation and the additional keys after it's run.
