### ISSUE TITLE
FILE NOT FOUND error

### ISSUE THREAD

**Issue by ogbogutc** [krathjen/studiolibrary#245]
Hello Team, 
       We would first like to say that we are simply blown away by Studio Library after being introduced to the Maya plugin, and honestly wonder how we have gone so long without such a wonderful plugin addition to our pipeline.
        Today, we tested it proper with a few of our rigs, and encountered a problem. 

Here is what we did: 

1. We opened the character file in Maya, attached the Facecap .fbx file to the Advanced Skeleton Facial controls (single click button operation). 
2. We then baked out the animation of the facial controls which we selected, before hitting SAVE in the plugin window.
3. We open a new scene ( also tried an animated scene) and selected thesame facial controls, then Applied the previously exported facial animation file. 

4 . the error comes up: Item Error: File not found.

We tried this across several machines with same error results.
. Both referenced and non-referenced rigs gave same error.

We had a single success out of more than 10 different trials. 

We would really like your help in solving this problem, as we would really like to fully test and integrate this plugin into our current project and pipeline

Thank you so much, and we look forward to hearing from you soon.

MEL SCRIPT PRINTOUT below as follows

// studiolibrarymaya.animitem : Loading: D:/Week_work/Studio Library Folder/OGA/Facetest_MB.anim
# Traceback (most recent call last):
#   File "C:\Users\Utricle 3\Documents\maya\scripts\studiolibrary-2.5.7\src\studiolibrarymaya\baseloadwidget.py", line 190, in accept
#     self.item().loadFromCurrentOptions()
#   File "C:\Users\Utricle 3\Documents\maya\scripts\studiolibrary-2.5.7\src\studiolibrarymaya\baseitem.py", line 508, in loadFromCurrentOptions
#     **kwargs
#   File "C:\Users\Utricle 3\Documents\maya\scripts\studiolibrary-2.5.7\src\mutils\decorators.py", line 133, in wrapped
#     return fn(*args, **kwargs)
#   File "C:\Users\Utricle 3\Documents\maya\scripts\studiolibrary-2.5.7\src\studiolibrarymaya\animitem.py", line 197, in load
#     sourceTime=(sourceStart, sourceEnd)
#   File "C:\Users\Utricle 3\Documents\maya\scripts\studiolibrary-2.5.7\src\mutils\decorators.py", line 42, in wrapped
#     ret = fn(*args, **kwargs)
#   File "C:\Users\Utricle 3\Documents\maya\scripts\studiolibrary-2.5.7\src\mutils\decorators.py", line 133, in wrapped
#     return fn(*args, **kwargs)
#   File "C:\Users\Utricle 3\Documents\maya\scripts\studiolibrary-2.5.7\src\mutils\animation.py", line 746, in load
#     srcCurves = self.open()
#   File "C:\Users\Utricle 3\Documents\maya\scripts\studiolibrary-2.5.7\src\mutils\decorators.py", line 55, in wrapped
#     return fn(*args, **kwargs)
#   File "C:\Users\Utricle 3\Documents\maya\scripts\studiolibrary-2.5.7\src\mutils\decorators.py", line 102, in wrapped
#     return fn(*args, **kwargs)
#   File "C:\Users\Utricle 3\Documents\maya\scripts\studiolibrary-2.5.7\src\mutils\animation.py", line 512, in open
#     namespace=Animation.IMPORT_NAMESPACE,
# RuntimeError: File not found.

**Comment by krathjen** [comment]
Hey @ogbogutc,

Thanks for the information.

I'll try and have a look over the next few days.

Cheers,

Kurt

**Comment by krathjen** [comment]
Hi @ogbogutc,

Do you see any Maya files in the following directory? 

`D:/Week_work/Studio Library Folder/OGA/Facetest_MB.anim`

If not, what files do you see? There may have been an error while saving.

Thanks,

Kurt

**Comment by Jammnation** [comment]
Hi @krathjen @ogbogutc 

I am so sorry to interject. I'm a student experimenting with studio library an encountered a similar problem to what is being described here. I see there has not been another post here for quite some time and I was wondering if you had discovered a fix for the problem?

When I follow the directory to where the animation should be saved out there is only a .json pose file and no Maya file. I've attempted to save the animation over 20 times but there has not been an instance where it saves out a Maya file.

Do you know what could possibly cause an error while saving? I have tested it on a different referenced rig and it worked for that one.

If you have any thoughts on what could be preventing the animation from saving out please let me know.

Thanks so much,

Jordan

**Comment by JoelH-Anim** [comment]
I recently had this same issue and found a solution! Hopefully it can work for you too. 

- In the Maya file, check your Animation Layers and make sure the "Base Animation Layer" is **unlocked**. 

Locking the base layer creates all sorts of weird problems with Maya's behavior and that happened to be the fix for my Studio Library saving the animation (It's best practice never to lock that layer at all!). After the base animation layer is unlocked, re-capture the animation. 

You can double check if it worked by going into your Studio Library folder, (you can find the path by accessing "Settings" in Studio Library) and opening the folder for your recent capture. Inside you should see an "animation.ma" (or .mb) file. 

Additionally, if you're working with anim layers in general, be sure to merge them down for best results. This is optional, but gets rid of that variable. 

Cheers

**Comment by charlesjoshi** [comment]
Hello @JoelH-Anim
Unlocking base layer solved the same issue for me too!!!!
Thank you so much 🙌
