### ISSUE TITLE
No folder selected. Please select a destination folder.

### ISSUE THREAD

**Issue by OleguerOrtiz** [krathjen/studiolibrary#255]
Last SL version on Maya 2018 Windows 10

When I try to save a pose or animation I receive this message. The folder has already been setted.
![image](https://user-images.githubusercontent.com/57137228/67763880-fcf4c600-fa48-11e9-8945-070049358ff1.png)

**Comment by krathjen** [comment]
Hi @OleguerOrtiz 

Are you still having issues?

You will need to create a folder first from the top left plus icon/button. 

Please see the following video for more information...

https://www.youtube.com/watch?v=lpaWrT7VXfM

Cheers,

Kurt

**Comment by OleguerOrtiz** [comment]
Hi Kurt,

I've already created the folder and still have the problem.

Any idea?

Regards,

Obtén l'Outlook per a l'Android<https://aka.ms/ghei36>

________________________________

**Comment by krathjen** [comment]
Hi @OleguerOrtiz,

Does the following screencast example help? 

![example](https://user-images.githubusercontent.com/8162617/73143360-3ba02800-40ed-11ea-958d-bba6d38cf7f3.gif)

**Comment by OleguerOrtiz** [comment]
Hi,

Not really as the error you send is for having no objects selected. My problem is about root folder configuration.

Regards

Obtén l'Outlook per a l'Android<https://aka.ms/ghei36>

________________________________

**Comment by L0Lock** [comment]
Hi!

I'm having the same issue, but I can't create a folder at all:

![demo gif](https://i.imgur.com/Nr4Zibs.gif)

Maybe that's the issue?

Here's the script editor output, it all apreas when I click "Ok":
```python
Traceback (most recent call last):
#   File "L:\loicd\Downloads\studiolibrary-2.7.1\src\studiolibrary\folderitem.py", line 352, in showSaveWidget
#     item.safeSave()
#   File "L:\loicd\Downloads\studiolibrary-2.7.1\src\studioqt\decorators.py", line 24, in wrapped
#     return fn(*args, **kwargs)
#   File "L:\loicd\Downloads\studiolibrary-2.7.1\src\studiolibrary\libraryitem.py", line 647, in safeSave
#     tmp = studiolibrary.createTempPath(self.__class__.__name__)
#   File "L:\loicd\Downloads\studiolibrary-2.7.1\src\studiolibrary\utils.py", line 389, in createTempPath
#     os.makedirs(path)
#   File "C:\Program Files\Autodesk\Maya2019\bin\python27.zip\os.py", line 150, in makedirs
#   File "C:\Program Files\Autodesk\Maya2019\bin\python27.zip\os.py", line 150, in makedirs
#   File "C:\Program Files\Autodesk\Maya2019\bin\python27.zip\os.py", line 150, in makedirs
#   File "C:\Program Files\Autodesk\Maya2019\bin\python27.zip\os.py", line 157, in makedirs
# WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: u'c:/users/loicd/appdata/local/temp/StudioLibrary/c:'

```

**Comment by OleguerOrtiz** [comment]
That was the problem thanks!.
No idea why you cannot create a folder.

Thanks!

S'ha enviat des de l'Outlook per a mòbils<https://aka.ms/blhgte>

________________________________

**Comment by L0Lock** [comment]
It looks like the install.mel doesn't install the plugin per say, it just adds a shelf button directing to wherever the plugin was unpacked.
Maybe that's intended, but then the documentation should specify you should unpack the zip file into Maya's script/plugins directory instead. Or at least in a specific folder that shouldn't be deleted, unlike what a lot of users do when they download a zip for an installation.

**Comment by L0Lock** [comment]
Considering the last error line:
```python
# WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: u'c:/users/loicd/appdata/local/temp/StudioLibrary/c:'
```
I noticed the path doesn't make any sense: why on earth is there `/c:` at the end of a path?  
Since it's the path obtained by src\studiolibrary\utils.py at line 389, I looked this file, noticed it works from a "tempPath" value set in /src/studiolibrary/config/default.json

Here the path is set to `{temp}/StudioLibrary/{user}`. I don't know why the wildcard `{user}` generates `/c:`, I guess it is supposed to pick up the user's name or something. I don't know.  
But considering the default {temp} path is already user-specific (at least on Windows: `C:\Users\username\AppData\Local\Temp`), I thought the `{user}` was just redundant and such, unnecessary?

So I duplicated the `default.json` file, named it `config.json` so it works as a custom overrided config file, then went to line 28 and removed the `/{user}` from the tempPath value, which is now:  `{temp}/StudioLibrary`.

After a fresh installation of StudioLibrary, **I can now create folders**.  
So I guess I found the core of the issue and a quick way to fix it user-side. I don't know if it's a reliable solution for everyone or if it breaks something, but it seems to work for me and maybe it might work for other too.
