### ISSUE TITLE
constant maya crash during install

### ISSUE THREAD

**Issue by superconcombre** [krathjen/studiolibrary#317]
Hi,
I am using Maya 2020.4 full version, and every time I click on the shelf to install, it crashes Maya. Unfortunately, I really need Studio Library for working remotely :/.
I forgot to add that I am using a Microsoft Surface pro 7, i7, 16g Ram. It has an integrated graphic card Intel Iris plus, instead of a regular graphic card. Everything else is running smoothly, only thing that crashes is Studio Library.
Thanks!

**Comment by krathjen** [comment]
Hi @superconcombre ,

Thanks for your comment.

Have you tried downloading the latest version (2.9.0) from the following link...

https://github.com/krathjen/studiolibrary

You will need to click the `Code` button and then `Download .zip`

Thanks,

Kurt

**Comment by superconcombre** [comment]
Thanks for your quick reply.
I have tried with the studiolibrary-master version (dunno if it's the 2.9.0 though) and it is still crashing. Seems to happen when the Qt is loading.
If that could help, when I open Maya I have this on my Output window:
OpenCL evaluator failed to find OpenCL device with vendor Intel(R) Corporation.

Here is the specs of the computer:
Quad-core 10th Gen Intel® Core™ i7-1065G7 Processor
Intel® Iris™ Plus Graphics

Thanks again for your support. It is really appreciated.

**Comment by mattivilho** [comment]
I can confirm having the same issue. Just downloaded the latest (2.9.0) version from here: https://github.com/krathjen/studiolibrary

Using Maya 2020 on a Windows 10.

**Comment by superconcombre** [comment]
Still waiting for some help, mattivilho... 
So not sure how to proceed, and I definitely need it for work unfortunately.

**Comment by ericweiss** [comment]
I am getting this error on install with Maya 2022

# Error: AttributeError: file E:\Downloads\studiolibrary-2.7.1\studiolibrary-2.7.1\src\studiolibrary\utils.py line 568: 'str' object has no attribute 'decode'

**Comment by krathjen** [comment]
Hi,

Please try downloading the latest version 2.9.3 from the following link...

https://github.com/krathjen/studiolibrary

Click the green `Code` button and then `Download Zip`

Thanks

**Comment by superconcombre** [comment]
Hi krathjen,
Thanks for your support, but it is still crashing Maya on me when trying to install...

**Comment by p00psicle** [comment]
I too have a crash on first run attempt. I've installed the last 5 or 6 versions. I click and *blink* maya is gone.

Maybe there's a log I can look at and some prerequisites I should have? A python install? Any ideas?

**Comment by mohler47** [comment]
I started having this same issue very recently. Even after a fresh install of Windows and Maya, the issue persists. Running low on options to debug on my own. Any possibility this could be a hardware issue? Only started having problems after upgrading my PC, but have no performance problems, and Maya simply closes when trying to load Studio Library or other tools, like Anim Bot.

**Comment by kkish2021** [comment]
> I started having this same issue very recently. Even after a fresh install of Windows and Maya, the issue persists. Running low on options to debug on my own. Any possibility this could be a hardware issue? Only started having problems after upgrading my PC, but have no performance problems, and Maya simply closes when trying to load Studio Library or other tools, like Anim Bot.

I was having the same problem with Studio Library, but still have the same thing with AnimBot. I fixed SL by changing in the config in src\studiolibrary\config and at the bottom changing the "analyticsEnabled" to false.

I did end up finding an error in windows Event Viewer when crashing from AnimBot, saying Faulting module path: C:\Program Files\Autodesk\Maya2020\Python\DLLs\_hashlib.pyd. Not too sure what that's supposed to be, but It seems to crash once it gets there for some reason. Maybe the two are related, but it might be something to look into.

**Comment by AlexTG14** [comment]
Hi guys I've found a solution here:  https://support.foundry.com/hc/en-us/articles/360012750300-Q100573-Katana-Mari-and-Nuke-can-fail-to-launch-with-a-10th-or-11th-Generation-Intel-CPU

We've recently updated our machines to Intel's 11th Gen and some maya scripts (including StudioLib) didn't work, so I've been searching about that and it points to an OpenSSL issue in 11th Gen.
https://software.intel.com/content/www/us/en/develop/articles/openssl-sha-crash-bug-requires-application-update.html

You need to set a new Environment Variable in Windows 10 (Control Panel > System > Advanced System Settings > Environment Variables) and create a new variable:

-name : OPENSSL_ia32cap
-value : ~0x200000200000000

![openSSL_issue_11th](https://user-images.githubusercontent.com/89795172/131365970-7e2e06a8-3f60-45f7-b46d-35e8832dad88.PNG)

Hope it helps... :)

Alex

**Comment by guttoes** [comment]
> Hi guys I've found a solution here: https://support.foundry.com/hc/en-us/articles/360012750300-Q100573-Katana-Mari-and-Nuke-can-fail-to-launch-with-a-10th-or-11th-Generation-Intel-CPU
> 
> We've recently updated our machines to Intel's 11th Gen and some maya scripts (including StudioLib) didn't work, so I've been searching about that and it points to an OpenSSL issue in 11th Gen.
> https://software.intel.com/content/www/us/en/develop/articles/openssl-sha-crash-bug-requires-application-update.html
> 
> You need to set a new Environment Variable in Windows 10 (Control Panel > System > Advanced System Settings > Environment Variables) and create a new variable:
> 
> -name : OPENSSL_ia32cap
> -value : ~0x200000200000000
> 
> ![openSSL_issue_11th](https://user-images.githubusercontent.com/89795172/131365970-7e2e06a8-3f60-45f7-b46d-35e8832dad88.PNG)
> 
> Hope it helps... :)
> 
> Alex


This worked for me! for maya 2018 and 2019.

**Comment by naiem35** [comment]
> 
> 
> Hi guys I've found a solution here: https://support.foundry.com/hc/en-us/articles/360012750300-Q100573-Katana-Mari-and-Nuke-can-fail-to-launch-with-a-10th-or-11th-Generation-Intel-CPU
> 
> We've recently updated our machines to Intel's 11th Gen and some maya scripts (including StudioLib) didn't work, so I've been searching about that and it points to an OpenSSL issue in 11th Gen. https://software.intel.com/content/www/us/en/develop/articles/openssl-sha-crash-bug-requires-application-update.html
> 
> You need to set a new Environment Variable in Windows 10 (Control Panel > System > Advanced System Settings > Environment Variables) and create a new variable:
> 
> -name : OPENSSL_ia32cap -value : ~0x200000200000000
> 
> ![openSSL_issue_11th](https://user-images.githubusercontent.com/89795172/131365970-7e2e06a8-3f60-45f7-b46d-35e8832dad88.PNG)
> 
> Hope it helps... :)
> 
> Alex

Thank you very much. It works for me.

**Comment by idrusdados** [comment]
> > Hi guys I've found a solution here: https://support.foundry.com/hc/en-us/articles/360012750300-Q100573-Katana-Mari-and-Nuke-can-fail-to-launch-with-a-10th-or-11th-Generation-Intel-CPU
> > We've recently updated our machines to Intel's 11th Gen and some maya scripts (including StudioLib) didn't work, so I've been searching about that and it points to an OpenSSL issue in 11th Gen.
> > https://software.intel.com/content/www/us/en/develop/articles/openssl-sha-crash-bug-requires-application-update.html
> > You need to set a new Environment Variable in Windows 10 (Control Panel > System > Advanced System Settings > Environment Variables) and create a new variable:
> > -name : OPENSSL_ia32cap
> > -value : ~0x200000200000000
> > ![openSSL_issue_11th](https://user-images.githubusercontent.com/89795172/131365970-7e2e06a8-3f60-45f7-b46d-35e8832dad88.PNG)
> > Hope it helps... :)
> > Alex
> 
> This worked for me! for maya 2018 and 2019.

worked as well For maya 2020. thank you so much, guys,

**Comment by matthew60707** [comment]
Hi!! 
It's no work for me. I need some help, please 
The maya show me this error.
# UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal, at line 14, in "C:\Program Files\Autodesk\Maya2020\bin\maya.exe"
# Error: Error in  maya.utils._guiExceptHook:
#   File "C:\Program Files\Autodesk\Maya2020\Python\lib\site-packages\maya\utils.py", line 351, in formatGuiException
#     result = u'%s: file %s line %s: %s' % (exceptionType.__name__, file, line, exceptionMsg)
# UnicodeDecodeError: 'ascii' codec can't decode byte 0xa4 in position 26: ordinal not in range(128)
# 
# Original exception was:
# Traceback (most recent call last):
#   File "<maya console>", line 18, in <module>
#   File "C:\Users\MATTHEW\OneDrive\Document\maya\scripts\studiolibrary-master\src\studiolibrary\main.py", line 45, in main
#     libraryWindow = mayalibrarywindow.MayaLibraryWindow.instance(*args, **kwargs)
#   File "C:\Users\MATTHEW\OneDrive\Document\maya\scripts\studiolibrary-master\src\studiolibrary\librarywindow.py", line 169, in instance
#     libraryWindow = cls(name=name)
#   File "C:\Program Files\Autodesk\Maya2020\Python\lib\site-packages\maya\app\general\mayaMixin.py", line 258, in __init__
#     super(MayaQWidgetDockableMixin, self).__init__(parent=parent, *args, **kwargs) # Init all baseclasses (including QWidget) of the main class
#   File "C:\Program Files\Autodesk\Maya2020\Python\lib\site-packages\maya\app\general\mayaMixin.py", line 78, in __init__
#     super(MayaQWidgetBaseMixin, self).__init__(parent=parent, *args, **kwargs) # Init all baseclasses (including QWidget) of the main class
#   File "C:\Users\MATTHEW\OneDrive\Document\maya\scripts\studiolibrary-master\src\studiolibrary\librarywindow.py", line 411, in __init__
#     self.updatePreviewWidget()
#   File "C:\Users\MATTHEW\OneDrive\Document\maya\scripts\studiolibrary-master\src\studiolibrary\librarywindow.py", line 1720, in updatePreviewWidget
#     self.setPreviewWidgetFromItem(self._currentItem, force=True)
#   File "C:\Users\MATTHEW\OneDrive\Document\maya\scripts\studiolibrary-master\src\studiolibrary\librarywindow.py", line 1742, in setPreviewWidgetFromItem
#     self.clearPreviewWidget()
#   File "C:\Users\MATTHEW\OneDrive\Document\maya\scripts\studiolibrary-master\src\studiolibrary\librarywindow.py", line 1715, in clearPreviewWidget
#     widget = studiolibrary.widgets.PlaceholderWidget()
#   File "C:\Users\MATTHEW\OneDrive\Document\maya\scripts\studiolibrary-master\src\studiolibrary\widgets\placeholderwidget.py", line 22, in __init__
#     studioqt.loadUi(self)
#   File "C:\Users\MATTHEW\OneDrive\Document\maya\scripts\studiolibrary-master\src\studioqt\utils.py", line 115, in loadUi
#     widget.ui = QtCompat.loadUi(path, widget)
#   File "C:\Users\MATTHEW\OneDrive\Document\maya\scripts\studiolibrary-master\src\studiovendor\Qt.py", line 849, in _loadUi
#     ui = loader.load(path, widget)
# RuntimeError: Unable to open/read ui device #

**Comment by RezaM1364** [comment]
Hi

You need to set a new Environment Variable in Windows 10 (Control Panel >
System > Advanced System Settings > Environment Variables) and create a new
variable:
-name : OPENSSL_ia32cap-value : ~0x200000200000000

It didn't work for me on Windows 11

It was executed with the above method and it worked

**Comment by matthew60707** [comment]
@RezaM1364 @AlexTG14 
I am currently using Win11 and my maya version is 2020.4
I still can't use the above method before, I would like to ask if it is because of win11

**Comment by peanuts** [comment]
> Hi guys I've found a solution here: https://support.foundry.com/hc/en-us/articles/360012750300-Q100573-Katana-Mari-and-Nuke-can-fail-to-launch-with-a-10th-or-11th-Generation-Intel-CPU
> 
> We've recently updated our machines to Intel's 11th Gen and some maya scripts (including StudioLib) didn't work, so I've been searching about that and it points to an OpenSSL issue in 11th Gen. https://software.intel.com/content/www/us/en/develop/articles/openssl-sha-crash-bug-requires-application-update.html
> 
> You need to set a new Environment Variable in Windows 10 (Control Panel > System > Advanced System Settings > Environment Variables) and create a new variable:
> 
> -name : OPENSSL_ia32cap -value : ~0x200000200000000
> 
> ![openSSL_issue_11th](https://user-images.githubusercontent.com/89795172/131365970-7e2e06a8-3f60-45f7-b46d-35e8832dad88.PNG)
> 
> Hope it helps... :)
> 
> Alex

Nice to working!
Think you so much~

**Comment by youngfra** [comment]
@mattivilho hey hi. Have you managed to solve the problem? I.m into the same situation

**Comment by RezaM1364** [comment]
Hi

I solved the bug of studiolibrary  not running from here.

I did not understand exactly about your system.

Check the solutions in this link. I hope the problem will be solved

https://github.com/krathjen/studiolibrary/issues/317#issuecomment-1376438710

**Comment by RezaM1364** [comment]
hi

yes



I solved the bug of studiolibrary  not running from here.

I did not understand exactly about your system.

Check the solutions in this link. I hope the problem will be solved

https://github.com/krathjen/studiolibrary/issues/317#issuecomment-1376438710

**Comment by matthew60707** [comment]
Thanks you for your response ☺️


RezaM1364 ***@***.***> 於 2023年6月30日 週五 21:01 寫道：

> hi
>
> yes
>
>
>
> I solved the bug of studiolibrary not running from here.
>
> I did not understand exactly about your system.
>
> Check the solutions in this link. I hope the problem will be solved
>
>
> https://github.com/krathjen/studiolibrary/issues/317#issuecomment-1376438710
>

**Comment by youngfra** [comment]
hey hi. Have you managed to solve the problem? I'm into the same situation @matthew60707

**Comment by RezaM1364** [comment]
Hi guys I've found a solution here:
https://support.foundry.com/hc/en-us/articles/360012750300-Q100573-Katana-Mari-and-Nuke-can-fail-to-launch-with-a-10th-or-11th-Generation-Intel-CPU

We've recently updated our machines to Intel's 11th Gen and some maya
scripts (including StudioLib) didn't work, so I've been searching about
that and it points to an OpenSSL issue in 11th Gen.
https://software.intel.com/content/www/us/en/develop/articles/openssl-sha-crash-bug-requires-application-update.html

You need to set a new Environment Variable in Windows 10 (Control Panel >
System > Advanced System Settings > Environment Variables) and create a new
variable:

-name : OPENSSL_ia32cap
-value : ~0x200000200000000

[image: openSSL_issue_11th]
<https://user-images.githubusercontent.com/89795172/131365970-7e2e06a8-3f60-45f7-b46d-35e8832dad88.PNG>

Hope it helps... :)

Alex

**Comment by harasho9161** [comment]
![2024y02m24d_182933680](https://github.com/krathjen/studiolibrary/assets/159735872/87180075-83b6-4f67-9df7-14c2aa9120e1)
Hello
I added a new one to the environment variables, but I can't install it.
I need help.
Windows 11 Home.
13th Gen Intel(R) Core(TM) i7-13700F.
Attached is a screenshot of the error screen.
