### ISSUE TITLE
[2.16.0] Unable to capture thumbnail

### ISSUE THREAD

**Issue by cblanchette97** [krathjen/studiolibrary#475]
Hey guys, we recently updated our studiolibrary version to the 2.16.0 release offered [here](https://www.studiolibrary.com/downloads).

We are now facing an issue that prevents us from capturing a thumbnail from the "New Pose" action:

![image](https://github.com/user-attachments/assets/fc905045-8ace-47c4-934a-f02b380330dd)

Here is more details in the traceback:

```
# Result: <studiolibrarymaya.mayalibrarywindow.MayaLibraryWindow(0x1d201a60, name="studiolibrary_8715fd62_062f_4270_8558_ef391041660e") at 0x7fd99ad84f80> # 
# Traceback (most recent call last):
#   File "/squeeze/software-dc/prod/rez/pkgs/ext/maya_studiolibrary/2.16.0/platform-linux/maya-2022/studiolibrarymaya/basesavewidget.py", line 405, in thumbnailCapture
#     captured=self._capturedCallback,
#   File "/squeeze/software-dc/prod/rez/pkgs/ext/maya_studiolibrary/2.16.0/platform-linux/maya-2022/mutils/gui/thumbnailcapturedialog.py", line 84, in thumbnailCapture
#     step=step,
#   File "/squeeze/software-dc/prod/rez/pkgs/ext/maya_studiolibrary/2.16.0/platform-linux/maya-2022/mutils/gui/thumbnailcapturedialog.py", line 120, in __init__
#     parent = parent or mutils.gui.mayaWindow()
#   File "/squeeze/software-dc/prod/rez/pkgs/ext/maya_studiolibrary/2.16.0/platform-linux/maya-2022/mutils/gui/__init__.py", line 36, in mayaWindow
#     return QtCompat.wrapInstance(int(mainWindowPtr), QtWidgets.QMainWindow)
#   File "/squeeze/software-dc/prod/rez/pkgs/ext/maya_studiolibrary/2.16.0/platform-linux/maya-2022/studiovendor/Qt.py", line 678, in _wrapinstance
#     assert isinstance(ptr, long), "Argument 'ptr' must be of type <long>"
# AssertionError: Argument 'ptr' must be of type <long>
```

Please let me know if there is anything we can do on our end to fix this.

Thanks!

**Comment by cblanchette97** [comment]
To add some more details, we are using Maya-2022.5

**Comment by krathjen** [comment]
Hey @cblanchette97,

Thanks for creating the issue. I'd be happy to take a closer look. Do you mind sending an email to support@studiolibrary.com? It will make it easier to connect directly.

Cheers,

Kurt

**Comment by cblanchette97** [comment]
Hey, here's my work email if you want to keep in touch
